char H5libhdf5_settings[] =
		"        SUMMARY OF THE HDF5 CONFIGURATION\n"
				"        =================================\n"
				"\n"
				"General Information:\n"
				"-------------------\n"
				"                   HDF5 Version: 1.10.5\n"
				"                  Configured on: 2019-12-21\n"
				"                  Configured by: MinGW Makefiles\n"
				"                    Host system: Windows-10.0.17134\n"
				"              Uname information: Windows\n"
				"                       Byte sex: little-endian\n"
				"             Installation point: C:/Program Files/HDF_Group/HDF5/1.10.5\n"
				"\n"
				"Compiling Options:\n"
				"------------------\n"
				"                     Build Mode: RelWithDebInfo\n"
				"              Debugging Symbols: \n"
				"                        Asserts: \n"
				"                      Profiling: \n"
				"             Optimization Level: \n"
				"\n"
				"Linking Options:\n"
				"----------------\n"
				"                      Libraries: \n"
				"  Statically Linked Executables: OFF\n"
				"                        LDFLAGS: \n"
				"                     H5_LDFLAGS: \n"
				"                     AM_LDFLAGS: \n"
				"                Extra libraries: \n"
				"                       Archiver: D:/Program Files/mingw64/bin/ar.exe\n"
				"                         Ranlib: D:/Program Files/mingw64/bin/ranlib.exe\n"
				"\n"
				"Languages:\n"
				"----------\n"
				"                              C: yes\n"
				"                     C Compiler: D:/Program Files/mingw64/bin/gcc.exe 8.1.0\n"
				"                       CPPFLAGS: \n"
				"                    H5_CPPFLAGS: \n"
				"                    AM_CPPFLAGS: \n"
				"                         CFLAGS:  -std=c99  -fstdarg-opt -pedantic -Wall -Wextra -fmessage-length=0\n"
				"                      H5_CFLAGS: \n"
				"                      AM_CFLAGS: \n"
				"               Shared C Library: YES\n"
				"               Static C Library: YES\n"
				"\n"
				"                        Fortran: OFF\n"
				"               Fortran Compiler:  \n"
				"                  Fortran Flags: \n"
				"               H5 Fortran Flags: \n"
				"               AM Fortran Flags: \n"
				"         Shared Fortran Library: YES\n"
				"         Static Fortran Library: YES\n"
				"\n"
				"                            C++: ON\n"
				"                   C++ Compiler: D:/Program Files/mingw64/bin/g++.exe 8.1.0\n"
				"                      C++ Flags: \n"
				"                   H5 C++ Flags: \n"
				"                   AM C++ Flags: \n"
				"             Shared C++ Library: YES\n"
				"             Static C++ Library: YES\n"
				"\n"
				"                            JAVA: OFF\n"
				"                   JAVA Compiler:  \n"
				"\n"
				"Features:\n"
				"---------\n"
				"                   Parallel HDF5: OFF\n"
				"Parallel Filtered Dataset Writes: \n"
				"              Large Parallel I/O: \n"
				"              High-level library: ON\n"
				"                    Threadsafety: OFF\n"
				"             Default API mapping: v110\n"
				"  With deprecated public symbols: ON\n"
				"          I/O filters (external): \n"
				"                             MPE: \n"
				"                      Direct VFD: \n"
				"                         dmalloc: \n"
				"  Packages w/ extra debug output: \n"
				"                     API Tracing: OFF\n"
				"            Using memory checker: OFF\n"
				" Memory allocation sanity checks: OFF\n"
				"          Function Stack Tracing: OFF\n"
				"       Strict File Format Checks: OFF\n"
				"    Optimization Instrumentation: \n";

